// Emoji specifiche per singolo prodotto, organizzate per categoria (stesse categorie
// di DIZIONARIO in categorie.js). Non sostituisce la categoria: è solo per la
// visualizzazione. Estendibile aggiungendo voci qui, "prodotto: 'emoji'".
const PRODUCT_ICONS = {
  frutta: {
    mela: '🍎', mele: '🍎', pera: '🍐', pere: '🍐', banana: '🍌', banane: '🍌',
    arancia: '🍊', arance: '🍊', limone: '🍋', limoni: '🍋', lime: '🍋',
    fragola: '🍓', fragole: '🍓', uva: '🍇', kiwi: '🥝', mango: '🥭',
    ananas: '🍍', melone: '🍈', anguria: '🍉', pesca: '🍑', pesche: '🍑',
    albicocca: '🍑', albicocche: '🍑', prugna: '🍑', prugne: '🍑',
    ciliegia: '🍒', ciliegie: '🍒', mandarino: '🍊', mandarini: '🍊',
    clementina: '🍊', clementine: '🍊', pompelmo: '🍊', avocado: '🥑',
    lampone: '🍇', lamponi: '🍇', mirtillo: '🫐', mirtilli: '🫐',
    melograno: '🍎', fico: '🍇', fichi: '🍇', dattero: '🍇', datteri: '🍇',
    cocco: '🥥', papaya: '🍈', maracuja: '🍈', litchi: '🍇', nespola: '🍑',
    cachi: '🍅', insalata: '🥬', lattuga: '🥬', rucola: '🥬', spinaci: '🥬',
    pomodoro: '🍅', pomodori: '🍅', ciliegino: '🍅', cetriolo: '🥒',
    cetrioli: '🥒', peperone: '🫑', peperoni: '🫑', zucchina: '🥒',
    zucchine: '🥒', melanzana: '🍆', melanzane: '🍆', carota: '🥕',
    carote: '🥕', sedano: '🥬', finocchio: '🥬', broccolo: '🥦',
    broccoli: '🥦', cavolfiore: '🥦', cavolo: '🥬', 'cavolo cappuccio': '🥬',
    'cavolo nero': '🥬', cipolla: '🧅', cipolle: '🧅', cipollotto: '🧅',
    aglio: '🧄', scalogno: '🧅', patata: '🥔', patate: '🥔', zucca: '🎃',
    funghi: '🍄', porcini: '🍄', champignon: '🍄', shiitake: '🍄',
    asparagi: '🥬', carciofi: '🥬', radicchio: '🥬', piselli: '🫛',
    fagiolini: '🫛', fave: '🫘', ceci: '🫘', lenticchie: '🫘', mais: '🌽',
    barbabietola: '🥔', rapa: '🥔', bietola: '🥬', porro: '🧅',
    'prezzemolo fresco': '🌿', 'basilico fresco': '🌿', 'menta fresca': '🌿',
  },
  carne: {
    pollo: '🍗', 'petto di pollo': '🍗', 'cosce di pollo': '🍗',
    'ali di pollo': '🍗', tacchino: '🦃', 'fesa di tacchino': '🦃',
    manzo: '🥩', maiale: '🥓', vitello: '🥩', agnello: '🍖', coniglio: '🐇',
    anatra: '🦆', faraona: '🍗', salsiccia: '🌭', salsicce: '🌭',
    würstel: '🌭', wurstel: '🌭', bratwurst: '🌭', bresaola: '🥓',
    'prosciutto cotto': '🥓', 'prosciutto crudo': '🥓', salame: '🥓',
    mortadella: '🥓', speck: '🥓', pancetta: '🥓', guanciale: '🥓',
    coppa: '🥓', lonza: '🥓', lardo: '🥓', nduja: '🌶️', cotoletta: '🍖',
    fettine: '🥩', bistecca: '🥩', hamburger: '🍔', polpette: '🍖',
    arrosto: '🍖', costine: '🍖', petto: '🍗', stinco: '🍖', ossobuco: '🍖',
    trippa: '🍖', fegato: '🍖', cuore: '🍖', carpaccio: '🥩', tartare: '🥩',
    'roast beef': '🥩',
  },
  pesce: {
    salmone: '🐟', tonno: '🐟', merluzzo: '🐟', branzino: '🐟', orata: '🐟',
    spigola: '🐟', acciughe: '🐟', sardine: '🐟', sgombro: '🐟',
    aringa: '🐟', alici: '🐟', gamberi: '🦐', mazzancolle: '🦐',
    scampi: '🦐', gamberetti: '🦐', gamberoni: '🦐', vongole: '🦪',
    cozze: '🦪', calamari: '🦑', polpo: '🐙', seppie: '🦑', totani: '🦑',
    sogliola: '🐟', halibut: '🐟', trota: '🐟', baccalà: '🐟',
    'pesce spada': '🐟', dentice: '🐟', rombo: '🐟', 'rana pescatrice': '🐟',
    cernia: '🐟', ricciola: '🐟', palamita: '🐟', aragosta: '🦞',
    granchio: '🦀', astice: '🦞', granciporro: '🦀', bottarga: '🐟',
    'tonno in scatola': '🐟', 'salmone affumicato': '🐟',
    'sgombro in scatola': '🐟',
  },
  latticini: {
    latte: '🥛', 'latte intero': '🥛', 'latte parzialmente scremato': '🥛',
    'latte scremato': '🥛', 'latte di mandorla': '🥛', 'latte di soia': '🥛',
    'latte di avena': '🥛', 'latte di riso': '🥛', 'latte condensato': '🥛',
    'latte in polvere': '🥛', yogurt: '🥣', 'yogurt greco': '🥣',
    'yogurt bianco': '🥣', 'yogurt alla frutta': '🥣', kefir: '🥛',
    burro: '🧈', panna: '🥛', 'panna da cucina': '🥛', 'panna fresca': '🥛',
    'panna montata': '🥛', mozzarella: '🧀', burrata: '🧀',
    'mozzarella di bufala': '🧀', 'fior di latte': '🧀', parmigiano: '🧀',
    'parmigiano reggiano': '🧀', pecorino: '🧀', grana: '🧀',
    'grana padano': '🧀', gorgonzola: '🧀', ricotta: '🧀', brie: '🧀',
    camembert: '🧀', emmental: '🧀', asiago: '🧀', provola: '🧀',
    scamorza: '🧀', fontina: '🧀', philadelphia: '🧀', stracchino: '🧀',
    crescenza: '🧀', mascarpone: '🧀', 'fiocchi di latte': '🧀',
    robiola: '🧀', taleggio: '🧀', groviera: '🧀', uova: '🥚',
    'uova di gallina': '🥚', 'uova biologiche': '🥚',
  },
  pane: {
    pane: '🍞', 'pane integrale': '🍞', 'pane in cassetta': '🍞',
    'pan carré': '🍞', 'pane di segale': '🍞', 'pane multicereali': '🍞',
    'pane senza glutine': '🍞', 'pane ai cereali': '🍞', panini: '🍞',
    rosette: '🍞', ciabatta: '🍞', baguette: '🥖', michette: '🍞',
    grissini: '🥖', crackers: '🍘', 'crackers integrali': '🍘',
    'fette biscottate': '🍞', 'fette biscottate integrali': '🍞',
    focaccia: '🍞', pizzette: '🍕', 'pizzette rosse': '🍕', brioche: '🥐',
    cornetto: '🥐', croissant: '🥐', 'pan brioche': '🥐', taralli: '🥨',
    freselle: '🍞', piadina: '🫓', tortilla: '🫓', muffin: '🧁',
    plumcake: '🍰', torta: '🎂', crostata: '🥧', 'pasta sfoglia': '🥐',
    'pasta frolla': '🥐', biscotti: '🍪', 'biscotti al burro': '🍪',
    'biscotti integrali': '🍪', cantucci: '🍪', amaretti: '🍪',
    farina: '🌾', 'farina 00': '🌾', 'farina integrale': '🌾',
    'farina di mais': '🌾', 'farina di riso': '🌾', 'farina di mandorle': '🌾',
    'farina di ceci': '🌾', 'farina senza glutine': '🌾', lievito: '🌾',
    'lievito di birra': '🌾', 'lievito in polvere': '🌾', bicarbonato: '🧂',
    zucchero: '🍬', 'zucchero a velo': '🍬', 'zucchero di canna': '🍬',
    'zucchero semolato': '🍬', cacao: '🍫', cioccolato: '🍫',
    'cioccolato fondente': '🍫', 'cioccolato al latte': '🍫',
    nutella: '🍫', marmellata: '🍯', confettura: '🍯', miele: '🍯',
    sciroppo: '🍯',
  },
  pasta: {
    pasta: '🍝', spaghetti: '🍝', spaghettini: '🍝', 'spaghetti integrali': '🍝',
    rigatoni: '🍝', penne: '🍝', 'penne rigate': '🍝', fusilli: '🍝',
    farfalle: '🍝', linguine: '🍝', tagliatelle: '🍝', lasagne: '🍝',
    gnocchi: '🍝', tortellini: '🥟', ravioli: '🥟', orecchiette: '🍝',
    bucatini: '🍝', 'mezze penne': '🍝', tortiglioni: '🍝', conchiglie: '🍝',
    paccheri: '🍝', vermicelli: '🍝', capellini: '🍝', fettuccine: '🍝',
    maltagliati: '🍝', trofie: '🍝', strozzapreti: '🍝', caserecce: '🍝',
    lumache: '🍝', 'mezze maniche': '🍝', "pasta all'uovo": '🍝',
    'pasta integrale': '🍝', 'pasta senza glutine': '🍝',
    'pasta di legumi': '🍝', 'pasta di farro': '🍝', 'pasta di riso': '🍝',
    'pasta di mais': '🍝', riso: '🍚', 'riso carnaroli': '🍚',
    'riso arborio': '🍚', 'riso basmati': '🍚', 'riso integrale': '🍚',
    'riso venere': '🍚', 'riso parboiled': '🍚', 'riso vialone nano': '🍚',
    risotto: '🍚', orzo: '🌾', farro: '🌾', 'cous cous': '🍚', bulgur: '🍚',
    quinoa: '🍚', polenta: '🌽', miglio: '🌾', 'grano saraceno': '🌾',
    avena: '🌾',
  },
  bevande: {
    acqua: '💧', 'acqua naturale': '💧', 'acqua frizzante': '💧',
    'acqua tonica': '💧', 'acqua aromatizzata': '💧', 'coca cola': '🥤',
    'coca cola zero': '🥤', fanta: '🥤', sprite: '🥤', pepsi: '🥤',
    aranciata: '🥤', limonata: '🍋', chinotto: '🥤', gassosa: '🥤',
    'ginger ale': '🥤', succo: '🧃', 'succo di frutta': '🧃',
    "succo d'arancia": '🧃', 'succo di mela': '🧃', nettare: '🧃',
    smoothie: '🥤', centrifugato: '🥤', tè: '🍵', 'tè freddo': '🧊',
    'tè verde': '🍵', 'tè nero': '🍵', 'tè alla pesca': '🍵',
    'tè al limone': '🍵', caffè: '☕', 'caffè in polvere': '☕',
    'caffè in capsule': '☕', 'caffè solubile': '☕', camomilla: '🍵',
    tisana: '🍵', infuso: '🍵', matcha: '🍵', birra: '🍺',
    'birra artigianale': '🍺', 'birra analcolica': '🍺', 'birra scura': '🍺',
    'birra chiara': '🍺', vino: '🍷', 'vino rosso': '🍷', 'vino bianco': '🍷',
    'vino rosato': '🍷', prosecco: '🥂', spumante: '🥂', champagne: '🍾',
    lambrusco: '🍷', amaro: '🥃', aperitivo: '🍹', aperol: '🍹',
    campari: '🍹', martini: '🍸', rum: '🥃', vodka: '🥃', gin: '🍸',
    whisky: '🥃', grappa: '🥃', limoncello: '🥃', 'energy drink': '🥤',
    kombucha: '🍹',
  },
  surgelati: {
    surgelati: '🧊', 'piselli surgelati': '🧊', 'spinaci surgelati': '🧊',
    'verdure surgelate': '🧊', 'patate surgelate': '🧊',
    'patatine surgelate': '🍟', 'bastoncini di pesce': '🐟',
    'cotolette surgelate': '🍖', 'lasagne surgelate': '🍝',
    'pizza surgelata': '🍕', 'minestrone surgelato': '🍲',
    'gamberetti surgelati': '🦐', 'calamari surgelati': '🦑',
    'frutta surgelata': '🧊', 'frutti di bosco surgelati': '🫐',
    'mais surgelato': '🌽', 'edamame surgelati': '🫛',
    'fagiolini surgelati': '🫛', 'broccoli surgelati': '🥦',
    'funghi surgelati': '🍄', 'zucchine surgelate': '🥒',
    'cornetti surgelati': '🥐', 'croissant surgelati': '🥐',
    'burger surgelato': '🍔', 'pollo surgelato': '🍗',
    'wurstel surgelati': '🌭',
  },
  gelati: {
    gelato: '🍨', gelati: '🍨', ghiacciolo: '🍧', ghiaccioli: '🍧',
    'cono gelato': '🍦', 'coppa gelato': '🍨', 'gelato alla crema': '🍨',
    'gelato al cioccolato': '🍫', 'gelato alla fragola': '🍓',
    'gelato alla vaniglia': '🍨', 'gelato al pistacchio': '🍨',
    'gelato al limone': '🍋', 'gelato alla nocciola': '🍨',
    'gelato stracciatella': '🍨', magnum: '🍦', 'cornetto algida': '🍦',
    calippo: '🍧', stecco: '🍦', 'sandwich gelato': '🍦',
    'fiordilatte gelato': '🍨', semifreddo: '🍨', 'torta gelato': '🎂',
  },
  caramelle: {
    caramelle: '🍬', caramella: '🍬', gomme: '🍬', 'chewing gum': '🍬',
    mentine: '🍬', 'tic tac': '🍬', cioccolatini: '🍫', kinder: '🍫',
    'kinder bueno': '🍫', 'kinder sorpresa': '🥚', 'kinder delice': '🍫',
    'ferrero rocher': '🍫', raffaello: '🍬', bounty: '🍫', snickers: '🍫',
    twix: '🍫', 'kit kat': '🍫', oreo: '🍪', ringo: '🍪', wafer: '🍫',
    'nutella biscuits': '🍪', 'pan di stelle': '🍪', chips: '🍟',
    patatine: '🍟', 'pop corn': '🍿', nachos: '🌮', popcorn: '🍿',
    noccioline: '🥜', arachidi: '🥜', pistacchi: '🥜', mandorle: '🥜',
    anacardi: '🥜', merendine: '🧁', snack: '🍪', barretta: '🍫',
    'barrette energetiche': '🍫', 'granola bar': '🍫', cereali: '🥣',
    'corn flakes': '🥣', müesli: '🥣', granola: '🥣',
    "fiocchi d'avena": '🥣', 'riso soffiato': '🥣',
  },
  salse: {
    maionese: '🥫', ketchup: '🍅', senape: '🌭', 'senape di digione': '🌭',
    'salsa worcester': '🫙', tabasco: '🌶️', sriracha: '🌶️', harissa: '🌶️',
    'salsa di soia': '🫙', 'salsa tamari': '🫙', 'salsa teriyaki': '🫙',
    'salsa agrodolce': '🫙', 'salsa tartara': '🫙', aioli: '🫙',
    'salsa rosa': '🫙', 'salsa cocktail': '🫙', pesto: '🌿',
    'pesto alla genovese': '🌿', 'pesto rosso': '🌿', 'pesto di rucola': '🌿',
    hummus: '🫘', guacamole: '🥑', tzatziki: '🥒', 'baba ganoush': '🍆',
    'salsa barbecue': '🫙', ranch: '🫙', 'salsa buffalo': '🌶️',
    'salsa al curry': '🍛', 'salsa verde': '🌿', chimichurri: '🌿',
    'salsa tonnata': '🐟',
  },
  sughi: {
    sugo: '🍅', 'sugo al pomodoro': '🍅', 'sugo al ragù': '🍅', ragù: '🍝',
    'sugo alla bolognese': '🍝', "sugo all'amatriciana": '🍝',
    'sugo alla norma': '🍝', 'sugo alle verdure': '🍅',
    'sugo al pesto': '🌿', "sugo all'arrabbiata": '🌶️',
    'sugo alle vongole': '🦪', 'sugo ai funghi': '🍄',
    'sugo al tartufo': '🍄', passata: '🍅', 'passata di pomodoro': '🍅',
    'pomodori pelati': '🍅', 'polpa di pomodoro': '🍅',
    'concentrato di pomodoro': '🍅', 'doppio concentrato': '🍅',
    'salsa pronta': '🍅', 'sugo pronto': '🍅',
  },
  pulizia: {
    detersivo: '🧴', 'detersivo piatti': '🧴', 'detersivo lavatrice': '🧴',
    'detersivo lavastoviglie': '🧴', 'pastiglie lavastoviglie': '🧼',
    'brillantante lavastoviglie': '🧴', 'sale lavastoviglie': '🧂',
    ammorbidente: '🧴', candeggina: '🧴', anticalcare: '🧴',
    sgrassatore: '🧴', 'detergente multiuso': '🧴', 'detergente bagno': '🧴',
    'detergente wc': '🧴', 'detergente pavimenti': '🧴',
    'detergente vetri': '🧴', alcol: '🧴', 'alcol etilico': '🧴',
    'alcol isopropilico': '🧴', 'sacchetti spazzatura': '🗑️',
    'sacchetti immondizia': '🗑️', 'buste differenziata': '🗑️',
    'carta igienica': '🧻', fazzoletti: '🧻', salviette: '🧻',
    'rotolo cucina': '🧻', 'carta assorbente': '🧻', spugna: '🧽',
    spugne: '🧽', pagliette: '🧽', 'scotch brite': '🧽', scopa: '🧹',
    mocio: '🧹', strofinaccio: '🧻', 'panno microfibra': '🧻',
    'guanti pulizia': '🧤', palette: '🧹', 'scopino bagno': '🧹',
  },
  igiene: {
    shampoo: '🧴', balsamo: '🧴', 'maschera capelli': '🧴',
    'olio capelli': '🧴', bagnoschiuma: '🧴', docciaschiuma: '🧴',
    sapone: '🧼', saponetta: '🧼', 'sapone liquido': '🧴',
    dentifricio: '🪥', spazzolino: '🪥', 'filo interdentale': '🪥',
    collutorio: '🪥', rasoi: '🪒', 'rasoi usa e getta': '🪒',
    'schiuma da barba': '🪒', 'gel da barba': '🪒', dopobarba: '🧴',
    deodorante: '🧴', 'deodorante spray': '🧴', 'deodorante roll on': '🧴',
    'crema corpo': '🧴', 'crema viso': '🧴', 'crema mani': '🧴',
    'crema piedi': '🧴', 'siero viso': '🧴', 'protezione solare': '🧴',
    doposole: '🧴', struccante: '🧴', 'acqua micellare': '🧴',
    cotone: '🧴', 'dischetti struccanti': '🧴', tamponi: '🧴',
    assorbenti: '🧴', 'assorbenti interni': '🧴', salvaslip: '🧴',
    preservativi: '🧴', pannolini: '🧷', 'pannolini pull-up': '🧷',
    'salviettine umide': '🧻', 'salviettine neonato': '🧻',
    'crema cambio pannolino': '🧴',
  },
  farmacia: {
    aspirina: '💊', tachipirina: '💊', brufen: '💊', ibuprofene: '💊',
    paracetamolo: '💊', efferalgan: '💊', antidolorifico: '💊',
    antinfiammatorio: '💊', antibiotico: '💊', antistaminico: '💊',
    antiacido: '💊', cerotti: '🩹', bende: '🩹', garze: '🩹',
    'garze sterili': '🩹', cerotto: '🩹', disinfettante: '🧴',
    betadine: '🧴', amuchina: '🧴', 'acqua ossigenata': '🧴',
    collirio: '💧', 'gocce nasali': '💧', 'spray nasale': '💧',
    'spray gola': '💧', sciroppo: '🍯', 'vitamina c': '💊',
    'vitamina d': '💊', 'vitamina b12': '💊', multivitaminico: '💊',
    integratore: '💊', magnesio: '💊', zinco: '💊', ferro: '💊',
    'omega 3': '💊', probiotici: '💊', melatonina: '💊', oki: '💊',
    moment: '💊', nurofen: '💊', voltaren: '💊', arnica: '💊',
    lassativo: '💊', antidiarroico: '💊', 'carbone attivo': '💊',
    'test covid': '🧪', termometro: '🌡️',
  },
  condimenti: {
    olio: '🫒', 'olio di oliva': '🫒', 'olio extravergine': '🫒',
    'olio evo': '🫒', 'olio di semi': '🫒', 'olio di girasole': '🫒',
    'olio di arachidi': '🫒', 'olio di mais': '🫒', 'olio di cocco': '🥥',
    aceto: '🍶', 'aceto balsamico': '🍶', 'aceto di vino rosso': '🍶',
    'aceto di vino bianco': '🍶', 'aceto di mele': '🍶', sale: '🧂',
    'sale fino': '🧂', 'sale grosso': '🧂', 'sale iodato': '🧂',
    'sale rosa': '🧂', pepe: '🌶️', 'pepe nero': '🌶️', 'pepe bianco': '🌶️',
    'pepe rosa': '🌶️', peperoncino: '🌶️', 'paprika dolce': '🌶️',
    'paprika affumicata': '🌶️', origano: '🌿', basilico: '🌿',
    rosmarino: '🌿', timo: '🌿', salvia: '🌿', prezzemolo: '🌿',
    alloro: '🌿', 'noce moscata': '🌰', curcuma: '🌶️', curry: '🍛',
    cannella: '🌶️', zafferano: '🌶️', cumino: '🌶️', cardamomo: '🌶️',
    'chiodi di garofano': '🌶️', anice: '🌶️', 'semi di sesamo': '🌰',
    'semi di chia': '🌰', 'semi di zucca': '🌰', 'semi di girasole': '🌻',
    'semi di lino': '🌰', dado: '🧂', 'dado vegetale': '🧂',
    'dado di pollo': '🧂', 'dado di manzo': '🧂', brodo: '🍲',
    'brodo di pollo': '🍲', 'brodo vegetale': '🍲', 'brodo di pesce': '🍲',
    capperi: '🫒', olive: '🫒', 'olive nere': '🫒', 'olive verdi': '🫒',
    tahin: '🫙', 'pasta di sesamo': '🫙', 'lievito alimentare': '🌾',
    'amido di mais': '🌽', maizena: '🌽',
  },
  animali: {
    crocchette: '🐾', 'crocchette cane': '🐶', 'crocchette gatto': '🐱',
    'cibo per cane': '🐶', 'cibo per gatto': '🐱', 'cibo umido cane': '🐶',
    'cibo umido gatto': '🐱', 'bustine gatto': '🐱', 'bustine cane': '🐶',
    'snack cane': '🐶', 'snack gatto': '🐱', dentastix: '🦴',
    'osso cane': '🦴', 'croccantini gatto': '🐱', 'paté gatto': '🐱',
    lettiera: '🐾', 'lettiera agglomerante': '🐾', 'lettiera silicio': '🐾',
    'shampoo cane': '🐶', 'shampoo gatto': '🐱', antiparassitario: '🐾',
    'pipette antiparassitarie': '🐾', 'collare antiparassitario': '🐾',
    'spray antiparassitario': '🐾', 'cibo per uccelli': '🐦',
    'cibo per pesci': '🐟', 'sabbia per cincillà': '🐾',
    'fieno per conigli': '🐰', 'pellet per conigli': '🐰',
  },
};

// Ritorna l'emoji più adatta per un prodotto: prima l'icona specifica del prodotto,
// poi l'emoji della categoria (fallback), infine 🛒 (fallback generico).
function getIconaProdotto(nome, categoriaId) {
  if (nome && typeof nome === 'string') {
    const q = nome.trim().toLowerCase();
    if (q) {
      if (categoriaId && PRODUCT_ICONS[categoriaId] && PRODUCT_ICONS[categoriaId][q]) {
        return PRODUCT_ICONS[categoriaId][q];
      }
      for (const parole of Object.values(PRODUCT_ICONS)) {
        if (parole[q]) return parole[q];
      }
    }
  }
  const cat = typeof getCategoriaById === 'function' ? getCategoriaById(categoriaId) : null;
  return (cat && cat.emoji) || '🛒';
}
